function Hd = chebychev2
%CHEBYCHEV2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
% Generated on: 07-Apr-2021 19:29:20

% Chebyshev Type II Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in kHz.
Fs = 100;  % Sampling Frequency

Fstop = 25;          % Stopband Frequency
Fpass = 45;          % Passband Frequency
Astop = 40;          % Stopband Attenuation (dB)
Apass = 2;           % Passband Ripple (dB)
match = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% Get the transfer function values.
[b, a] = tf(Hd);

% Convert to a singleton filter.
Hd = dfilt.df2(b, a);



% [EOF]
